[PythonVersions]

# Optional: minimum defaults to pychub minimum python compatibility (3.10)
min = "3.10"

# Optional: omitting/asterisk will get all versions including and above "min"
# Exceeding the major version of pychub is possible, but not guaranteed to work
# Defaults to staying within the major version of pychub
max = "<4.0"

# The version prefix values, and they also imply ABI types ("none" for "py")
types = ["py", "cp"]

# Accept universal python versions (e.g., pyX, where "X" is the python major version)
accept_universal = true

# Canonical CPython IDs you care about
# Add to the calculated list or specify only these
specific = ["py3"]

# Flag to use only the specific list (minus any excludes)
specific_only = false

# List of python versions to exclude (takes precedence)
excludes = ["cp310"]

[PythonVersions.android]
placeholder = true

[PythonVersions.ios]
placeholder = true

[PythonVersions.linux]
placeholder = true

[PythonVersions.macos]
placeholder = true

[PythonVersions.windows]
placeholder = true

[AbiValues]

# Include debug ("d") variants, like "cp312d"
include_debug = false

# To include the CPython stable "abi3"
include_stable = true

# Flag to use only the specific list (minus any excludes)
specific_only = false

# Add to the calculated list or specify only these
specific = [
    "cp310",
    "cp311",
    "cp312",
    "cp313",
    "py310",
    "py311",
    "py312",
    "py313"
]

# List of ABIs to exclude (takes precedence)
[AbiValues.excludes]
all = ["cp310d"]
android = []
ios     = []
linux   = []
macos   = []
windows = []

[PlatformValues.linux]
enabled = true

# Architectures for all variants
arches = ["x86_64", "aarch64"]

[PlatformValues.linux.manylinux]
enabled = true
min = "2.17"
max = "2.42"

[PlatformValues.linux.musllinux]
enabled = true
min = "1.1"
max = "*"

# Flag to use only the specific list (minus any excludes)
specific_only = false

# Extra explicit ones on top of the generated families
specific = [
  "manylinux_2_17_x86_64",
  "manylinux_2_17_aarch64",
  "musllinux_1_1_x86_64",
]

# List of platform values or patterns to exclude (takes precedence)
excludes = ["musllinux_1_1*"]

[PlatformValues.macOS]
# Not yet implemented
enabled = false

[PlatformValues.android]
# Not yet implemented
enabled = false

[PlatformValues.iOS]
# Not yet implemented
enabled = false

[CompatibilityTags]

# Flag to use only the specific list (minus any excludes)
specific_only = false

# Explicit list of tags to add. If the above settings are omitted, this list
# represents the full list of tags to include.
[CompatibilityTags.linux]

# Flag to use only the specific list (minus any excludes)
specific_only = false

specific = [
    "cp310-cp310-manylinux_2_17_x86_64",
    "cp310-abi3-manylinux_2_17_x86_64",
    "cp311-cp311-manylinux_2_17_x86_64",
    "cp311-abi3-manylinux_2_17_x86_64",
    "cp312-cp312-manylinux_2_17_x86_64",
    "cp312-abi3-manylinux_2_17_x86_64",
    "cp310-cp310-manylinux_2_17_aarch64",
    "cp310-abi3-manylinux_2_17_aarch64",
    "cp311-cp311-manylinux_2_17_aarch64",
    "cp311-abi3-manylinux_2_17_aarch64",
    "cp312-cp312-manylinux_2_17_aarch64",
    "cp312-abi3-manylinux_2_17_aarch64",
    "cp310-cp310-musllinux_1_1_x86_64",
    "cp310-abi3-musllinux_1_1_x86_64",
    "cp311-cp311-musllinux_1_1_x86_64",
    "cp311-abi3-musllinux_1_1_x86_64",
    "cp312-cp312-musllinux_1_1_x86_64",
    "cp312-abi3-musllinux_1_1_x86_64"
]

# Compatibility tag triples to exclude (takes precedence)
excludes = [
    "cp310-cp310-musllinux_1_1_x86_64",
    "cp310-cp310-musllinux_1_1_aarch64"
]
